### ISSUE TITLE
dockerize application

### ISSUE THREAD

**Issue by bartius-nigel** [bartius-nigel/weather-comparitor#43]

**Comment by elaynelemos** [comment]
Hey! I would like to work on it for hacktoberfest. :D

**Comment by bartius-nigel** [comment]
Hey thats fantastic! Im not a docker expert but let me know if you need anything.

**Comment by bartius-nigel** [comment]
> Hey! I would like to work on it for hacktoberfest. :D

Fantastic! Thanks! Im not a major docker guy but let me know if you need anything.

**Comment by elaynelemos** [comment]
> > Hey! I would like to work on it for hacktoberfest. :D
> 
> Fantastic! Thanks! Im not a major docker guy but let me know if you need anything.

Awesome! You can assign it to me if you want to.
